language: node_js
node_js:
  - node
before_install:
  # Use recent version of Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
  - (cd web-app && yarn)
